Traceback (most recent call last):
  File "main_graph.py", line 215, in <module>
    f1 = main(cfg)
  File "main_graph.py", line 163, in main
    test_f1 = graph_classification_evaluation(model, cfg.eval_T, pooler, eval_loader,
  File "/ddm-nni/REDDIT-B/evaluator.py", line 51, in graph_classification_evaluation
    out = model.embed(batch_g, feat, t)
  File "/ddm-nni/REDDIT-B/models/DDM.py", line 119, in embed
    _, hidden = self.net(g, x_t=x_t, time_embed=time_embed)
  File "/root/miniconda3/envs/nni/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/ddm-nni/REDDIT-B/models/mlp_gat.py", line 72, in forward
    h_t = self.down_layers[l](g, h_t)
  File "/root/miniconda3/envs/nni/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/nni/lib/python3.8/site-packages/dgl/nn/pytorch/conv/gatconv.py", line 253, in forward
    if (graph.in_degrees() == 0).any():
  File "/root/miniconda3/envs/nni/lib/python3.8/site-packages/dgl/heterograph.py", line 3435, in in_degrees
    deg = self._graph.in_degrees(etid, v_tensor)
  File "/root/miniconda3/envs/nni/lib/python3.8/site-packages/dgl/heterograph_index.py", line 669, in in_degrees
    _CAPI_DGLHeteroInDegrees(self, int(etype), F.to_dgl_nd(v))
  File "dgl/_ffi/_cython/./function.pxi", line 295, in dgl._ffi._cy3.core.FunctionBase.__call__
  File "dgl/_ffi/_cython/./function.pxi", line 227, in dgl._ffi._cy3.core.FuncCall
  File "dgl/_ffi/_cython/./function.pxi", line 217, in dgl._ffi._cy3.core.FuncCall3
dgl._ffi.base.DGLError: [08:01:23] /opt/dgl/src/runtime/cuda/cuda_device_api.cc:116: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading: CUDA: out of memory
Stack trace:
  [bt] (0) /root/miniconda3/envs/nni/lib/python3.8/site-packages/dgl/libdgl.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x4f) [0x7fa7d591403f]
  [bt] (1) /root/miniconda3/envs/nni/lib/python3.8/site-packages/dgl/libdgl.so(dgl::runtime::CUDADeviceAPI::AllocDataSpace(DGLContext, unsigned long, unsigned long, DGLDataType)+0x260) [0x7fa7d5dd79d0]
  [bt] (2) /root/miniconda3/envs/nni/lib/python3.8/site-packages/dgl/libdgl.so(dgl::runtime::NDArray::Empty(std::vector<long, std::allocator<long> >, DGLDataType, DGLContext)+0x177) [0x7fa7d5c45847]
  [bt] (3) /root/miniconda3/envs/nni/lib/python3.8/site-packages/dgl/libdgl.so(dgl::aten::COOSort(dgl::aten::COOMatrix, bool)+0x22a) [0x7fa7d593f6aa]
  [bt] (4) /root/miniconda3/envs/nni/lib/python3.8/site-packages/dgl/libdgl.so(dgl::aten::CSRMatrix dgl::aten::impl::COOToCSR<(DGLDeviceType)2, long>(dgl::aten::COOMatrix)+0xc8) [0x7fa7d5e06418]
  [bt] (5) /root/miniconda3/envs/nni/lib/python3.8/site-packages/dgl/libdgl.so(dgl::aten::COOToCSR(dgl::aten::COOMatrix)+0x3f3) [0x7fa7d58fc7e3]
  [bt] (6) /root/miniconda3/envs/nni/lib/python3.8/site-packages/dgl/libdgl.so(dgl::UnitGraph::GetInCSR(bool) const+0xbd) [0x7fa7d5d98acd]
  [bt] (7) /root/miniconda3/envs/nni/lib/python3.8/site-packages/dgl/libdgl.so(dgl::UnitGraph::GetFormat(dgl::SparseFormat) const+0x4d) [0x7fa7d5d99fdd]
  [bt] (8) /root/miniconda3/envs/nni/lib/python3.8/site-packages/dgl/libdgl.so(dgl::UnitGraph::InDegrees(unsigned long, dgl::runtime::NDArray) const+0x36) [0x7fa7d5d9b496]


